spring:
  cloud:
    gateway:
      mvc:
        routes:
          - id: auth-service
            uri: ${AUTH_SERVICE_URL:https://tms-authentication-service.onrender.com}
            predicates:
              - Path=/account/**
          - id: role-service
            uri: ${AUTh_SERVICE_URL:https://tms-authentication-service.onrender.com}
            predicates:
              - Path=/api/roles/**
          - id: customer-service
            uri: ${CUSTOMER_SERVICE_URL:https://tms-customer-service.onrender.com}
            predicates:
              - Path=/api/v1/customers/**
          - id: news-service
            uri: ${NEWS_SERVICE_URL:https://tms-news-service.onrender.com}
            predicates:
              - Path=/v1/api/news/**
            # ASP.NET Core — dùng URL trực tiếp
          - id: container-service
            uri: ${FLEET_SERVICE_URL:https://tms-fleet-service.onrender.com}
            predicates:
              - Path=/api/container/**
          - id: driver-service
            uri: ${FLEET_SERVICE_URL:https://tms-fleet-service.onrender.com}
            predicates:
              - Path=/api/driver/**
          - id: vehicle-service
            uri: ${FLEET_SERVICE_URL:https://tms-fleet-service.onrender.com}
            predicates:
              - Path=/api/vehicle/**
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://discovery-service:8061/eureka}
  instance:
    hostname: ${EUREKA_INSTANCE_HOSTNAME:apiGateway-service}
    prefer-ip-address: false
    instance-id: ${spring.application.name}:${server.port}

server:
  port: 8060

app:
  jwtSecret: aEgC6orb0GXD2sQwg2Vn3aTiVqmDMUtset7wi8mFJcY
  jwtExpirationMs: 86400000
management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: never