spring:
  data:
    mongodb:
      uri: mongodb+srv://20102004hinh_db_user:ZgHZZxMA4YsmKxx0@logistic-application.hv6w0bm.mongodb.net/authentication_service?appName=Logistic-Application&tls=true&tlsInsecure=false

    redis:
      url: rediss://default:gQAAAAAAAsEVAAIgcDJjNTk5Y2RkODE1Mzk0ZWJmOWFlNWNlYjZkMWI0NzBmMA@related-louse-180501.upstash.io:6379

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - email
              - profile

          github:
            client-id: ${GITHUB_CLIENT_ID}
            client-secret: ${GITHUB_CLIENT_SECRET}
            scope:
              - user:email

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8061/eureka}

server:
  port: 9000

app:
  jwtSecret: aEgC6orb0GXD2sQwg2Vn3aTiVqmDMUtset7wi8mFJcY
  jwtExpirationMs: 86400000
