server:
  port: 8061

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

logging:
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss}){blue} %clr(${LOG_LEVEL_PATTERN:-%5p}) %m%n"

spring:
  output:
    ansi:
      enabled: always

management:
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: never