server:
  port: 8061

eureka:
  instance:
    hostname: discovery-service
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://discovery-service:8061/eureka
logging:
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss}){blue} %clr(${LOG_LEVEL_PATTERN:-%5p}) %m%n"
spring:
  output:
    ansi:
      enabled: always

management:
  tracing:
    sampling:
      probability: 1.0
  web:
    exposure:
      include: health
  endpoint:
    health:
      show-details: never