server:
  port: 9003
spring:
  data:
    redis:
      host: localhost
      port: 6379
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8061/eureka
gnews:
  api:
    key: ${GNEWS_API_KEY}
    url: https://gnews.io/api/v4