server:
  port: 9003
spring:
  data:
    redis:
      url: rediss://default:gQAAAAAAAsEVAAIgcDJjNTk5Y2RkODE1Mzk0ZWJmOWFlNWNlYjZkMWI0NzBmMA@related-louse-180501.upstash.io:6379
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://discovery-service:8061/eureka}
    instance:
      hostname: ${EUREKA_INSTANCE_HOSTNAME:customer-service}
      prefer-ip-address: false
      instance-id: ${spring.application.name}:${server.port}  
gnews:
  api:
    key: ${GNEWS_API_KEY}
    url: https://gnews.io/api/v4
