server:
  port: 9003
spring:
  data:
    redis:
      host: localhost
      port: 6379
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8061/eureka
gnews:
  api:
    key: 825313cfafa1ba60727dcfe81725bac8
    url: https://gnews.io/api/v4
management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: never