spring.application.name=config_service
spring.profiles.active=native
spring.profiles.output.ansi.enabled=always
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n
server.port=8088
