spring.application.name=Authentication_Service

spring.data.mongodb.uri=mongodb://authentication_service:mongo123@localhost:27017/authentication_service?authSource=admin

server.port=9000

app.jwtSecret=aEgC6orb0GXD2sQwg2Vn3aTiVqmDMUtset7wi8mFJcY
app.jwtExpirationMs=86400000

# config for redis
spring.data.redis.host=localhost
spring.data.redis.port=6379