spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: authentication-service
          uri: lb://authentication-service
          predicates:
            - Path=/api/authentication/**
        - id: customer-service
          uri: lb://customer-service
          predicates:
            - Path=/api/customer/**
eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8061/eureka

server:
  port: 8060